export const THEME = {
  card: {
    container: "bg-white border border-gray-200 rounded-xl p-4 md:p-5 transition-all shadow-3xs",
    interactive: "bg-white border border-gray-200 rounded-xl p-4 md:p-5 transition-all hover:bg-gray-50/40 hover:border-gray-300 shadow-3xs",
    header: "border-b border-gray-100 pb-4 mb-4",
    title: "text-gray-800 font-bold text-sm uppercase tracking-wider mb-1 flex items-center gap-1.5 leading-none",
    overlay: "fixed inset-0 z-50 overflow-y-auto px-4 py-12 bg-black/40 backdrop-blur-xs flex items-center justify-center",
    modal: "bg-white border border-gray-250 rounded-2xl p-6 w-full max-w-md shadow-2xl relative select-none animate-fade-in text-left",
  },

  button: {
    primary: "bg-blue-600 hover:bg-blue-700 text-white font-bold uppercase text-[9px] tracking-wider py-2.5 px-5 rounded-lg cursor-pointer transition-colors flex items-center justify-center gap-1 shadow-xs font-mono disabled:opacity-50 disabled:cursor-not-allowed",
    secondary: "bg-gray-100 hover:bg-gray-200 text-gray-700 font-bold uppercase text-[9px] tracking-wider py-2.5 px-4 rounded-lg cursor-pointer transition-colors disabled:opacity-50 disabled:cursor-not-allowed",
    outline: "bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 hover:text-gray-800 font-bold uppercase text-[9px] tracking-wider py-2 px-3 rounded-lg flex items-center gap-1 cursor-pointer transition-colors max-md:flex-1 justify-center shadow-3xs",
    danger: "bg-red-50 border border-red-200 hover:bg-red-100 text-red-700 font-bold uppercase text-[9px] tracking-wider py-2 px-3 rounded-lg flex items-center gap-1 cursor-pointer transition-colors max-md:flex-1 justify-center shadow-3xs",
    link: "text-xs text-gray-500 hover:text-gray-800 font-bold uppercase transition-colors cursor-pointer",
    tabActive: "px-3 py-1.5 rounded-lg transition-colors cursor-pointer font-bold bg-blue-600 text-white shadow-3xs",
    tabInactive: "px-3 py-1.5 rounded-lg transition-colors cursor-pointer font-bold text-gray-600 hover:text-gray-900",
  },

  input: {
    text: "w-full bg-white border border-gray-200 rounded-lg p-2.5 text-xs text-gray-850 placeholder-gray-400 focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none font-semibold",
    textSmall: "w-full bg-white border border-gray-200 rounded-lg p-2 text-xs text-gray-805 placeholder-gray-400 focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none font-semibold",
    textarea: "w-full bg-white border border-gray-200 rounded-lg p-2.5 text-xs text-gray-850 placeholder-gray-400 focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none font-medium",
    textareaSmall: "w-full bg-white border border-gray-200 rounded-lg p-2 text-xs text-gray-805 placeholder-gray-400 focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none font-medium",
    select: "w-full bg-white border border-gray-200 rounded-lg p-2.5 text-xs text-gray-850 focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none font-bold cursor-pointer",
    selectSmall: "w-full bg-white border border-gray-200 rounded-lg p-2 text-xs text-gray-805 focus:border-blue-600 focus:ring-1 focus:ring-blue-600 outline-none font-bold cursor-pointer",
    label: "text-[10px] text-gray-500 uppercase tracking-wider block font-bold mb-1",
    labelSmall: "text-[9px] text-gray-500 uppercase tracking-wider block font-semibold mb-1 truncate",
  },

  badge: {
    success: "text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-green-50 text-green-700 border border-green-200",
    warning: "text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-yellow-50 text-yellow-700 border border-yellow-250",
    neutral: "text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-gray-100 text-gray-550 border border-gray-200",
    danger: "text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-red-50 text-red-700 border border-red-250",
    category: "text-[10px] text-blue-600 font-bold uppercase",
  },

  header: {
    navbar: "sticky top-0 z-50 bg-white border-b border-gray-250/80 px-4 py-3.5 md:px-8 flex flex-col md:flex-row items-center justify-between gap-4 select-none shadow-xs",
    logoWrapper: "flex items-center justify-between w-full md:w-auto",
    logoButton: "flex items-center gap-1 cursor-pointer group",
    logoSvg: "w-40 h-10 md:w-44 md:h-11 object-contain transition-all",
    mobileActions: "md:hidden flex items-center gap-2",
    mobileUserWrapper: "flex items-center gap-1.5",
    profileMobileBadge: "flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold hover:opacity-90 transition-opacity border",
    mobileLogoutBtn: "text-gray-500 hover:text-red-700 p-2 cursor-pointer rounded-lg hover:bg-slate-100 transition-colors",
    mobileGuestLoginBtn: "bg-blue-600 text-white hover:bg-blue-700 transition-all font-semibold uppercase text-xs tracking-wider px-4 py-2 rounded-full cursor-pointer shadow-sm",
    searchWrapper: "w-full md:max-w-md relative",
    searchIcon: "absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400",
    searchInput: "w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-full text-gray-800 placeholder-gray-400 text-sm focus:outline-none focus:border-blue-500 focus:bg-white focus:ring-1 focus:ring-blue-500/20 transition-all",
    searchClear: "absolute right-3.5 top-1/2 -translate-y-1/2 text-gray-400 hover:text-blue-600 text-xs font-bold",
    actionsWrapper: "flex items-center gap-3 w-full md:w-auto justify-end",
    simButton: "text-xs text-gray-600 hover:text-blue-600 transition-colors flex items-center gap-1.5 font-medium px-2.5 py-1.5 bg-white border border-gray-200 rounded-lg cursor-pointer max-md:w-full max-md:justify-center",
    simDropdown: "absolute top-10 right-0 bg-white border border-gray-200 rounded-xl p-2.5 shadow-xl flex flex-col gap-1.5 z-50 text-xs w-48 animate-in slide-in-from-top-2 duration-155",
    simItem: "flex items-center gap-2 w-full text-left p-1.5 rounded-md hover:bg-blue-50 text-gray-700 hover:text-blue-600 cursor-pointer transition-colors",
    realUserWrapper: "hidden md:flex items-center gap-3",
    realUserBtn: "flex items-center gap-2.5 text-right cursor-pointer group hover:opacity-90 transition-opacity",
    realUserMeta: "flex flex-col text-right",
    realUserName: "text-gray-800 text-xs font-semibold leading-tight max-w-[150px] truncate group-hover:text-blue-600 transition-colors",
    realUserAvatar: "w-8 h-8 rounded-full p-[1.5px] transition-transform group-hover:scale-105",
    realUserInitials: "w-full h-full rounded-full bg-white flex items-center justify-center text-xs font-bold border",
    logoutBtn: "text-gray-400 hover:text-blue-650 transition-colors p-1.5 cursor-pointer ml-1",
    loginBtn: "hidden md:flex items-center gap-2 bg-blue-600 text-white hover:bg-blue-700 transition-all font-semibold uppercase text-xs tracking-wider px-5 py-2 rounded-full cursor-pointer shadow-sm hover:scale-102",
  },

  footer: {
    container: "bg-white border-t border-gray-200 text-gray-500 py-12 px-6 mt-16 md:px-12 selection:bg-blue-600 selection:text-white",
    grid: "max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 items-start",
    columnStart: "flex flex-col gap-3 w-full",
    columnCenter: "flex flex-col gap-3 md:items-center w-full",
    columnEnd: "flex flex-col gap-3 md:items-end w-full",
    logoButton: "h-10 flex items-center justify-start cursor-pointer group",
    logoSvg: "w-40 h-10 object-contain transition-all",
    sectionHeaderStart: "h-10 flex items-center justify-start w-full",
    sectionHeaderCenter: "h-10 flex items-center justify-start md:justify-center w-full",
    sectionHeaderEnd: "h-10 flex items-center justify-start md:justify-end w-full",
    title: "text-gray-800 font-bold tracking-wide text-xs uppercase",
    navList: "text-sm flex flex-col gap-2 text-gray-500 md:items-center",
    link: "hover:text-blue-600 transition-colors",
    navButton: "hover:text-blue-600 transition-colors cursor-pointer text-left md:text-center font-medium",
    contactList: "text-sm flex flex-col gap-3 text-gray-500 md:items-end",
    contactItem: "flex items-center gap-2 md:flex-row-reverse",
    contactIcon: "w-5 text-blue-650 font-mono",
    contactMono: "font-mono md:text-right",
    contactText: "md:text-right",
    textMuted: "text-sm leading-relaxed text-gray-400 mt-2",
    textSmall: "text-xs text-gray-400 mt-1",
  },

  profileModal: {
    backdrop: "fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-xs select-none",
    card: "bg-white rounded-2xl border border-gray-200 overflow-hidden w-full max-w-lg shadow-2xl animate-in zoom-in-95 duration-100 flex flex-col max-h-[85vh] text-left",
    header: "p-5 border-b border-gray-150 flex items-center justify-between",
    avatar: "w-10 h-10 rounded-full flex items-center justify-center font-bold text-sm",
    metaTitle: "text-sm font-bold uppercase tracking-tight text-gray-800",
    metaBadge: "text-[10px] uppercase font-mono tracking-wider font-bold border px-2.5 py-0.5 rounded-full block w-fit mt-0.5",
    body: "p-6 overflow-y-auto flex-1",
    closeBtn: "text-gray-400 hover:text-gray-600 transition-colors rounded-full p-1 cursor-pointer",
    infoCard: "grid grid-cols-2 gap-y-4 gap-x-4 bg-gray-50 p-4 rounded-xl border border-gray-150",
    infoLabel: "text-[10px] text-gray-400 block uppercase tracking-wider font-semibold",
    infoValue: "text-gray-800 truncate block mt-1 font-bold",
    editForm: "flex flex-col gap-4",
    formActions: "flex gap-3 justify-end mt-4 border-t border-gray-100 pt-4",
    profileDetails: "flex flex-col gap-5 text-xs font-semibold",
    profileActions: "flex items-center gap-2.5 justify-end mt-2 pt-2 border-t border-gray-100",
    logoutDangerBtn: "bg-red-50 hover:bg-red-100 text-red-600 border border-red-200 text-[10px] font-bold uppercase tracking-wider px-4 py-2 rounded-lg transition-all cursor-pointer flex items-center gap-1.5 shadow-xs",
  },

  authModal: {
    overlay: "fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 selection:bg-blue-600 selection:text-white select-none",
    card: "bg-white border border-gray-200/80 rounded-3xl p-8 md:p-10 w-full max-w-[420px] shadow-2xl relative flex flex-col items-center text-gray-800",
    backButton: "absolute top-6 left-6 border border-gray-200 hover:border-blue-600 text-xs font-bold text-gray-600 hover:text-blue-600 uppercase py-1.5 px-4 rounded-full flex items-center gap-1 cursor-pointer transition-colors",
    logoWrapper: "mt-8 flex flex-col items-center gap-1 cursor-pointer",
    logoSvg: "w-44 h-11 object-contain transition-all",
    headingWrapper: "text-center mt-6 w-full",
    headingTitle: "text-2xl font-black text-gray-800 uppercase tracking-tight mt-1 leading-none",
    headingSubtitle: "text-gray-500 text-xs mt-2 leading-relaxed",
    form: "w-full flex flex-col gap-4",
    recoverCard: "bg-green-50 text-green-700 border border-green-200 p-4 rounded-xl flex flex-col items-center text-center gap-2 max-w-sm mt-2",
    recoverCardTitle: "font-bold text-xs",
    recoverCardText: "text-[10px] text-gray-500 leading-normal",
    recoverBackBtn: "text-white bg-green-650 hover:bg-green-700 hover:scale-101 text-[10px] uppercase font-bold py-1.5 px-4 rounded-full mt-2 transition-all cursor-pointer",
    block: "flex flex-col gap-3",
    label: "text-[10px] text-gray-450 uppercase tracking-widest font-bold block mb-1",
    labelAlt: "text-[10px] text-gray-400 uppercase tracking-widest font-bold block mb-1",
    labelWithGap: "text-[10px] text-gray-450 uppercase tracking-widest font-bold block mb-1.5",
    inputText: "w-full bg-white border border-gray-200 rounded-xl p-3 pr-10 text-xs text-gray-800 focus:outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-105 font-semibold",
    inputTextNoIcon: "w-full bg-white border border-gray-200 rounded-xl p-3 text-xs text-gray-800 focus:outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-105 font-semibold",
    inputEmailRecover: "w-full bg-white border border-gray-200 rounded-xl p-3 pr-10 text-xs text-gray-805 focus:outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-100 font-semibold",
    selectText: "w-full bg-white border border-gray-200 rounded-xl p-3 text-xs text-gray-805 font-semibold focus:outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-105",
    roleToggleWrap: "grid grid-cols-2 bg-gray-50 border border-gray-200 p-1 rounded-xl",
    roleToggleBtn: "py-1.5 rounded-lg text-xs font-bold uppercase transition-colors cursor-pointer",
    roleToggleActive: "bg-blue-600 text-white",
    roleToggleInactive: "text-gray-500 hover:text-gray-800",
    submitBtn: "w-full bg-blue-600 hover:bg-blue-700 text-white font-extrabold uppercase text-xs tracking-widest py-4 rounded-xl transition-all shadow-md active:scale-98 mt-2 cursor-pointer hover:scale-101",
    submitBtnSimple: "w-full bg-blue-600 text-white hover:bg-blue-700 font-extrabold uppercase py-3.5 rounded-xl text-xs tracking-wider transition-all mt-2 cursor-pointer",
    footerTextWrap: "text-center mt-6 text-xs text-gray-500",
    footerLink: "text-blue-600 hover:text-blue-700 font-extrabold transition-colors cursor-pointer capitalize",
    forgotBtn: "text-[10px] text-blue-605 hover:text-blue-700 font-extrabold tracking-tight cursor-pointer",
    passwordLabelRow: "flex items-center justify-between mb-1",
    passwordInput: "w-full bg-white border border-gray-200 rounded-xl p-3 pr-20 text-xs text-gray-800 focus:outline-none focus:border-blue-600 focus:ring-1 focus:ring-blue-105 font-semibold font-mono",
    passwordIcons: "absolute right-3.5 top-1/2 -translate-y-1/2 flex items-center gap-1.5 text-gray-450",
    eyeBtn: "hover:text-blue-600 transition-colors cursor-pointer",
  },

  eventGrid: {
    section: "max-w-7xl mx-auto px-4 md:px-8 mt-12 py-2 select-none selection:bg-blue-600 selection:text-white",
    headerWrap: "flex flex-col md:flex-row items-start md:items-center justify-between gap-4 mb-8",
    title: "text-3xl font-black uppercase text-gray-900 tracking-tight flex items-center gap-2",
    subtitle: "text-gray-400 text-xs mt-1 font-medium",
    tabsWrap: "flex bg-gray-100 border border-gray-200/85 p-1 rounded-full text-xs font-semibold",
    tabBtn: "px-4 py-1.5 rounded-full transition-all cursor-pointer",
    tabBtnActive: "bg-blue-600 text-white shadow-sm",
    tabBtnInactive: "text-gray-500 hover:text-gray-855",
    categoriesWrap: "flex gap-2 overflow-x-auto pb-4 scrollbar-none",
    categoryBtn: "px-5 py-2.5 rounded-full font-bold uppercase text-[11px] tracking-wider transition-all whitespace-nowrap cursor-pointer border",
    categoryBtnActive: "bg-blue-600 text-white border-blue-650 shadow-sm",
    categoryBtnInactive: "bg-white border-gray-200 text-gray-500 hover:text-blue-600 hover:bg-blue-50/30",
    emptyWrap: "w-full bg-white border border-gray-200 rounded-2xl py-16 px-4 text-center mt-6",
    emptyTitle: "text-gray-800 font-bold text-lg",
    emptyText: "text-gray-400 text-xs mt-1 max-w-sm mx-auto",
    cardsGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mt-6",
    card: "bg-white rounded-2xl overflow-hidden border border-gray-200/80 hover:border-blue-300 transition-all duration-300 group cursor-pointer flex flex-col justify-between hover:-translate-y-1 hover:shadow-md p-0 relative select-none shadow-xs",
    cardMediaWrap: "w-full h-44 overflow-hidden relative rounded-t-2xl",
    cardMedia: "w-full h-full object-cover transition-transform duration-500 group-hover:scale-[1.03]",
    cardMediaOverlay: "absolute inset-x-0 bottom-0 top-1/2 bg-gradient-to-t from-black/60 to-transparent",
    cardCategory: "absolute top-3 left-3 bg-blue-600 text-white font-extrabold text-[9px] uppercase tracking-wider py-1 px-2.5 rounded-full shadow-sm",
    cardPrice: "absolute bottom-3 right-3 bg-white/95 backdrop-blur-sm border border-gray-100 text-blue-650 font-black text-xs px-2.5 py-1 rounded-md shadow-xs",
    cardBody: "p-4 flex flex-col gap-2.5",
    cardTitle: "text-gray-800 font-bold text-sm tracking-tight group-hover:text-blue-600 transition-colors leading-tight line-clamp-2",
    cardMetaRow: "flex items-center gap-1.5 text-xs text-gray-500 font-medium",
    cardMetaRowSecondary: "flex items-center gap-1.5 text-xs text-gray-500",
    cardFooter: "border-t border-gray-100 p-4 pt-3 flex items-center justify-between text-[11px] text-gray-500 bg-gray-50/50",
    soldOut: "text-red-500 font-extrabold uppercase tracking-wider",
    seatsWrap: "flex items-center gap-1",
    seatsCount: "font-bold text-gray-700",
    ctaMini: "text-blue-600 font-bold flex items-center gap-0.5 group-hover:translate-x-1 transition-transform duration-300",
    highlightWrap: "w-full bg-gradient-to-r from-blue-900 to-slate-900 rounded-3xl p-8 md:p-12 flex flex-col md:flex-row items-center justify-between gap-8 mt-16 select-none relative overflow-hidden shadow-md",
    highlightGlow: "absolute right-0 top-0 w-80 h-80 bg-white/5 rounded-full blur-3xl -z-10 pointer-events-none",
    highlightBody: "flex flex-col gap-2 max-w-xl",
    highlightLabel: "text-xs text-blue-400 font-extrabold uppercase tracking-widest leading-none",
    highlightTitle: "text-3xl md:text-4xl font-extrabold tracking-tight text-white leading-none capitalize mt-1",
    highlightText: "text-xs md:text-sm text-gray-300 font-normal leading-relaxed mt-2",
    highlightBtn: "inline-flex bg-blue-600 hover:bg-blue-700 active:scale-97 text-white font-bold uppercase text-xs tracking-wider px-8 py-3.5 rounded-full transition-all cursor-pointer hover:scale-101 shadow-sm whitespace-nowrap animate-pulse",
    titleHighlight: "text-blue-600",
    emptyIcon: "w-12 h-12 text-gray-300 mx-auto mb-4",
    iconSmallBlue: "w-3.5 h-3.5 text-blue-500",
    iconSmallGray: "w-3.5 h-3.5 text-gray-400 shrink-0",
    arrowIconSmall: "w-3 h-3",
  },

  eventDetailModal: {
    overlay: "fixed inset-0 z-50 overflow-y-auto px-4 py-6 md:py-12 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center animate-fade-in select-none selection:bg-blue-600 selection:text-white",
    card: "bg-white border border-gray-200/80 w-full max-w-4xl rounded-2xl md:rounded-3xl shadow-2xl relative overflow-hidden flex flex-col md:flex-row max-h-[90vh] md:max-h-[85vh] text-gray-800",
    sidePanel: "md:w-5/12 bg-gray-50 flex flex-col justify-between border-r border-gray-150 relative",
    mediaWrap: "relative h-48 md:h-full md:absolute md:inset-0 bg-gray-55",
    mediaImage: "w-full h-full object-cover",
    mediaOverlay: "absolute inset-0 bg-gradient-to-t from-gray-900/90 via-gray-900/40 to-transparent",
    sideBody: "p-6 relative z-10 flex flex-col justify-end h-full text-white min-h-[160px]",
    categoryBadge: "text-white font-extrabold uppercase text-[10px] tracking-widest bg-blue-600 w-fit px-2.5 py-0.5 rounded-full mb-2",
    title: "text-xl md:text-2xl font-black tracking-tight uppercase leading-tight text-white mb-3",
    sideMetaList: "flex flex-col gap-2 text-xs text-gray-200",
    sideMetaRow: "flex items-center gap-2",
    sideMetaIcon: "w-4 h-4 text-blue-400 shrink-0",
    organizerWrap: "mt-4 pt-4 border-t border-white/20 flex items-center gap-2 text-[11px] text-gray-300",
    organizerAvatar: "w-6 h-6 rounded-full bg-blue-600 flex items-center justify-center text-[10px] font-bold text-white shrink-0",
    mobileCloseBtn: "md:hidden absolute top-4 right-4 bg-black/60 p-1.5 rounded-full text-white hover:bg-blue-600 transition-colors cursor-pointer",
    contentWrap: "flex-1 p-6 md:p-8 flex flex-col justify-between overflow-y-auto bg-white max-h-[60vh] md:max-h-full",
    desktopCloseBtn: "hidden md:flex absolute top-6 right-6 text-gray-405 hover:text-blue-600 transition-colors cursor-pointer",
    contentBody: "flex flex-col gap-6",
    sectionTitleMuted: "text-gray-400 font-bold text-xs uppercase tracking-wider mb-2",
    sectionText: "text-gray-600 text-xs leading-relaxed font-normal whitespace-pre-line text-justify",
    workshopsHeader: "flex items-center justify-between border-b border-gray-150 pb-2 mb-3",
    workshopsTitle: "text-gray-800 font-bold text-xs uppercase tracking-wider",
    workshopsHint: "text-[10px] text-gray-400",
    emptyWorkshops: "text-center p-4 bg-gray-50 border border-gray-200 rounded-xl",
    emptyWorkshopsText: "text-xs text-gray-505",
    workshopsList: "flex flex-col gap-3 max-h-[220px] overflow-y-auto pr-1 scrollbar-thin",
    workshopItem: "p-3 rounded-xl border transition-all flex items-start gap-3 cursor-pointer select-none",
    workshopItemActive: "bg-blue-50/50 border-blue-500/60 shadow-xs",
    workshopItemDefault: "bg-gray-50 border-gray-150 hover:border-gray-300",
    workshopItemDisabled: "opacity-55 cursor-not-allowed",
    workshopCheckWrap: "mt-0.5",
    workshopCheck: "w-4 h-4 rounded text-blue-600 bg-white border-gray-350 focus:ring-0 focus:ring-offset-0 focus:outline-none",
    workshopBody: "flex-1 flex flex-col gap-1 text-gray-700",
    workshopTop: "flex items-start justify-between gap-1.5",
    workshopName: "text-gray-800 font-bold text-xs leading-none group-hover:text-blue-600 transition-colors",
    workshopPrice: "text-[10px] font-mono font-bold text-blue-600 shrink-0",
    workshopDescription: "text-gray-500 text-[11px] leading-tight line-clamp-1",
    workshopMeta: "flex flex-wrap items-center gap-x-2 text-[10px] text-gray-400 mt-1",
    workshopInstructor: "font-semibold text-blue-600",
    workshopSpots: "text-gray-500",
    workshopSpotsSoldOut: "text-red-500",
    footerWrap: "mt-6 pt-4 border-t border-gray-150 flex flex-col gap-3",
    subtotalRow: "flex items-center justify-between text-xs text-gray-500",
    subtotalLeft: "flex flex-col",
    subtotalLabel: "font-mono text-[10px]",
    subtotalHint: "text-gray-400 text-[9px] mt-0.5",
    totalWrap: "text-right text-gray-800",
    totalLabel: "text-[10px] font-semibold block text-gray-500",
    totalValue: "text-xl font-black text-blue-600 font-mono",
    alreadyWrap: "flex flex-col gap-3",
    weekAlert: "bg-blue-50 border border-blue-150 p-2.5 rounded-xl flex items-start gap-2 text-blue-700 text-xs",
    weekAlertText: "leading-snug text-left",
    actionRow: "flex gap-3",
    secondaryActionBtn: "hidden md:block border border-gray-200 hover:bg-gray-55 text-gray-650 font-bold uppercase text-xs tracking-wider px-6 py-3.5 rounded-xl transition-all cursor-pointer",
    primaryActionBtn: "flex-1 bg-blue-600 hover:bg-blue-700 text-white font-extrabold uppercase text-xs tracking-widest py-4 rounded-xl transition-all cursor-pointer shadow-sm hover:scale-101 flex items-center justify-center gap-2",
    alreadyOk: "bg-green-50 border border-green-200 p-2.5 rounded-xl flex items-center justify-center gap-2 text-green-700 text-xs text-center w-full",
    guestHint: "text-[10px] text-gray-400 text-center italic mt-1",
  },

  sobreNos: {
    container: "max-w-4xl mx-auto px-4 py-12 select-none",
    backButton: "mb-8 text-xs text-blue-600 font-extrabold hover:underline flex items-center gap-1.5 uppercase tracking-wider font-mono cursor-pointer",
    backIcon: "w-3.5 h-3.5",
    heroWrap: "relative h-[300px] md:h-[400px] w-full rounded-2xl overflow-hidden mb-10 shadow-md",
    heroImage: "w-full h-full object-cover",
    heroOverlay: "absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-950/30 to-transparent",
    heroContent: "absolute bottom-6 left-6 md:bottom-10 md:left-10 z-10 text-white",
    heroBadge: "text-[10px] text-blue-400 font-extrabold uppercase tracking-widest font-mono bg-blue-950/50 backdrop-blur-md px-2.5 py-1 rounded-md",
    heroTitle: "text-3xl md:text-5xl font-black uppercase tracking-tight text-white mt-2 leading-tight",
    grid: "grid grid-cols-1 md:grid-cols-3 gap-8 text-gray-705",
    contentColumn: "md:col-span-2 flex flex-col gap-6",
    leadText: "text-base text-gray-700 font-medium leading-relaxed",
    bodyText: "text-sm text-gray-550 leading-relaxed",
    sideColumn: "flex flex-col gap-4",
    valuesCard: "bg-white border border-gray-150 p-5 rounded-2xl flex flex-col gap-3.5 shadow-xs",
    valuesHeader: "text-xs font-black text-gray-850 uppercase tracking-widest font-mono border-b border-gray-100 pb-2 flex items-center gap-1.5",
    valuesHeaderIcon: "w-4 h-4 text-blue-600",
    valuesList: "flex flex-col gap-3",
    valueItem: "flex items-start gap-2",
    valueIconWrap: "bg-blue-50 text-blue-600 p-1.5 rounded-lg shrink-0 mt-0.5",
    valueIcon: "w-3.5 h-3.5",
    valueTitle: "text-xs font-bold text-gray-800 uppercase tracking-tight",
    valueText: "text-[10px] text-gray-500 font-medium mt-0.5 leading-relaxed",
    contactCard: "bg-blue-50 border border-blue-100 p-5 rounded-2xl flex flex-col gap-2 select-none",
    contactTitle: "text-xs font-black text-blue-800 uppercase tracking-wide",
    contactText: "text-[11px] text-blue-700 leading-relaxed font-semibold",
  },

  politicaPrivacidade: {
    container: "max-w-3xl mx-auto px-4 py-12 select-none text-gray-700",
    backButton: "mb-8 text-xs text-blue-600 font-extrabold hover:underline flex items-center gap-1.5 uppercase tracking-wider font-mono cursor-pointer",
    backIcon: "w-3.5 h-3.5",
    headingWrap: "mb-10",
    headingBadge: "text-[10px] text-blue-600 font-extrabold uppercase tracking-widest font-mono",
    headingTitle: "text-3xl md:text-5xl font-black uppercase tracking-tight text-gray-900 mt-2 leading-tight",
    headingMeta: "text-xs text-gray-400 mt-2 font-mono uppercase tracking-wider font-bold",
    sectionsWrap: "border-t border-gray-150 pt-10 flex flex-col gap-8 text-sm leading-relaxed text-gray-650",
    section: "flex flex-col gap-3",
    sectionTitle: "text-xs font-black uppercase tracking-wider text-gray-950 flex items-center gap-1.5",
    sectionTitleNoIcon: "text-xs font-black uppercase tracking-wider text-gray-950",
    sectionIcon: "w-4 h-4 text-blue-600",
  },

  loginLanding: {
    page: "min-h-screen bg-slate-50 flex flex-col justify-between font-sans antialiased text-gray-800 select-none",
    grid: "flex-grow grid grid-cols-1 lg:grid-cols-2",
    bannerPane: "relative min-h-[420px] lg:min-h-0 bg-slate-900 text-white flex flex-col justify-between p-8 md:p-16 overflow-hidden",
    bannerImage: "absolute inset-0 w-full h-full object-cover opacity-40 pointer-events-none transition-all duration-300",
    bannerOverlay: "absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/50 to-slate-950/25 z-0",
    logoWrap: "relative z-10",
    logoCard: "bg-white/10 backdrop-blur-md p-3 rounded-xl border border-white/10 w-fit",
    logoImage: "w-40 h-10 object-contain",
    bannerBody: "relative z-10 mt-auto flex flex-col gap-4",
    bannerTag: "text-[10px] text-blue-400 font-extrabold uppercase tracking-widest font-mono flex items-center gap-1.5 leading-none",
    bannerTagIcon: "w-3.5 h-3.5",
    bannerTitle: "text-3xl md:text-5xl font-black uppercase tracking-tight text-white leading-tight",
    bannerSubtitle: "text-gray-200 text-xs md:text-sm leading-relaxed max-w-lg font-medium",
    bannerCta: "mt-4 bg-white/10 hover:bg-white/15 border border-white/20 hover:border-white/35 text-white text-[10px] font-bold uppercase tracking-wider py-2.5 px-4 rounded-xl cursor-pointer transition-all flex items-center gap-1.5 backdrop-blur-md w-fit",
    bannerCtaIcon: "w-3.5 h-3.5",
    bannerFootnote: "relative z-10 select-none text-[10px] text-gray-400 font-bold uppercase tracking-wider mt-8",
    formPane: "p-6 md:p-12 lg:p-16 flex flex-col justify-center bg-white border-l border-gray-150 min-h-full",
    formWrap: "w-full max-w-md mx-auto",
    headingWrap: "mb-6",
    headingTag: "text-[9px] text-blue-600 font-extrabold tracking-widest uppercase font-mono",
    headingTitle: "text-2xl font-black uppercase tracking-tight text-gray-850 mt-1",
    headingSubtitle: "text-xs text-gray-400 mt-2 leading-relaxed font-semibold",
    form: "flex flex-col gap-4",
    roleBlock: "flex flex-col gap-1",
    roleGrid: "grid grid-cols-2 gap-2 mt-1",
    roleButtonBase: "py-2 text-[10px] font-bold uppercase rounded-lg border transition-all cursor-pointer",
    roleButtonActive: "bg-blue-50 border-blue-500 text-blue-700",
    roleButtonInactive: "bg-white border-gray-200 text-gray-500 hover:bg-slate-50",
    fieldBlock: "flex flex-col gap-1",
    inlineGridTwo: "grid grid-cols-2 gap-2",
    inputIcon: "absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400",
    inputWithIcon: "pl-10 font-mono",
    submitBtn: "w-full bg-blue-600 hover:bg-blue-700 text-white text-[10px] font-bold uppercase tracking-wider py-3.5 rounded-xl cursor-pointer transition-all flex items-center justify-center gap-2 mt-2 shadow-xs group font-mono",
    submitIcon: "w-4 h-4 group-hover:translate-x-0.5 transition-transform",
    belowActions: "flex flex-col gap-3 text-center mt-4",
    toggleBtn: "text-xs text-blue-600 font-extrabold hover:underline cursor-pointer uppercase tracking-wider font-mono",
    dividerWrap: "relative flex py-2 items-center",
    dividerLine: "flex-grow border-t border-gray-150",
    dividerText: "flex-shrink mx-3 text-gray-400 text-[10px] uppercase font-bold tracking-wider",
    guestBtn: "text-gray-600 hover:text-blue-650 transition-colors cursor-pointer flex items-center justify-center gap-2 font-bold text-xs select-none border border-gray-250/70 hover:border-blue-300 py-3 rounded-xl bg-gray-50/50 hover:bg-gray-50",
    guestIcon: "w-4 h-4 text-blue-600 animate-spin-slow",
    demoCard: "border-t border-gray-150 pt-5 mt-8 bg-gray-50/40 p-4 rounded-xl border border-gray-150",
    demoTag: "text-[9px] text-amber-600 font-black tracking-wider uppercase block text-center mb-3",
    demoGrid: "grid grid-cols-2 gap-2",
    quickBtnBase: "bg-white border border-gray-150 transition-all p-2 rounded-lg text-left cursor-pointer flex flex-col items-start",
    quickBtnBlue: "hover:bg-blue-50/40 hover:border-blue-250",
    quickBtnGreen: "hover:bg-green-50/40 hover:border-green-250",
    quickBtnAmber: "hover:bg-yellow-50/40 hover:border-yellow-250",
    quickBtnPurple: "hover:bg-purple-50/40 hover:border-purple-250",
    quickRoleBlue: "text-[9px] font-black text-blue-600 uppercase tracking-widest font-mono",
    quickRoleGreen: "text-[9px] font-black text-green-600 uppercase tracking-widest font-mono",
    quickRoleAmber: "text-[9px] font-black text-amber-600 uppercase tracking-widest font-mono",
    quickRolePurple: "text-[9px] font-black text-purple-600 uppercase tracking-widest font-mono",
    quickName: "text-xs font-bold text-gray-800 truncate w-full mt-0.5",
    quickEmail: "text-[8px] text-gray-400 font-mono mt-0.5",
  },

  heroCarrossel: {
    emptyState: "w-full h-4 bg-transparent max-w-7xl mx-auto px-4 mt-6",
    section: "max-w-7xl mx-auto px-4 md:px-8 mt-6 select-none relative",
    card: "w-full overflow-hidden rounded-2xl md:rounded-3xl relative h-[320px] md:h-[420px] bg-gray-50 border border-gray-200/80 cursor-pointer group transition-all duration-500 shadow-sm",
    mediaWrap: "absolute inset-0 transition-transform duration-700 ease-out scale-100 group-hover:scale-[1.01]",
    mediaImage: "w-full h-full object-cover",
    mediaOverlay: "absolute inset-0 bg-gradient-to-r from-slate-950/90 via-slate-900/60 to-transparent z-10",
    contentWrap: "absolute inset-0 flex flex-col justify-end p-6 md:p-12 gap-3 z-20",
    eventMeta: "flex flex-wrap items-center gap-3 text-xs text-blue-200 font-semibold uppercase tracking-wider mb-1",
    eventCategory: "bg-blue-600 text-white px-2.5 py-0.5 rounded-full text-[10px]",
    eventMetaItem: "flex items-center gap-1",
    eventMetaLocation: "flex items-center gap-1 max-md:hidden",
    eventMetaIcon: "w-3.5 h-3.5",
    title: "text-3xl md:text-5xl font-black uppercase text-white tracking-tight leading-none drop-shadow-md",
    titleHighlight: "text-blue-400 block md:inline",
    titleDefault: "text-white",
    subtitle: "text-sm md:text-md text-gray-200 max-w-xl font-normal leading-relaxed drop-shadow",
    cta: "mt-2 text-xs md:text-sm text-blue-400 font-bold tracking-wide uppercase flex items-center gap-1.5 group-hover:text-blue-300 transition-colors",
    ctaArrow: "transform translate-x-0 group-hover:translate-x-1.5 transition-transform duration-300",
    navBtn: "absolute top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-black/30 hover:bg-blue-600 text-white flex items-center justify-center transition-all opacity-0 group-hover:opacity-100 cursor-pointer hidden md:flex border border-white/10 z-30",
    navPrev: "left-4",
    navNext: "right-4",
    navIcon: "w-5 h-5",
    dotsWrap: "absolute bottom-4 right-6 flex items-center gap-2 z-30",
    dotBase: "w-2.5 h-2.5 rounded-full transition-all cursor-pointer",
    dotActive: "bg-blue-500 w-6",
    dotInactive: "bg-white/40 hover:bg-white/60",
  },

  checkoutModal: {
    overlay: "fixed inset-0 z-50 overflow-y-auto px-4 py-6 md:py-12 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center animate-fade-in select-none selection:bg-blue-600 selection:text-white",
    card: "bg-white border border-gray-200/80 w-full max-w-4xl rounded-2xl md:rounded-3xl shadow-2xl relative overflow-hidden max-h-[92vh] md:max-h-[85vh] flex flex-col text-gray-800",
    header: "bg-gray-50 px-6 py-4 border-b border-gray-150 flex items-center justify-between",
    headerLeft: "flex items-center gap-2",
    headerIcon: "w-5 h-5 text-blue-600",
    headerTitle: "text-gray-900 font-extrabold text-sm uppercase tracking-wider",
    closeBtn: "text-gray-400 hover:text-blue-600 transition-colors cursor-pointer",
    closeIcon: "w-5 h-5",
    checkoutBody: "flex-1 overflow-y-auto p-6 md:p-8 grid grid-cols-1 md:grid-cols-2 gap-8 bg-white",
    leftColumn: "flex flex-col gap-5 border-r border-gray-100 pr-0 md:pr-8",
    sectionTitle: "text-gray-400 font-bold text-xs uppercase tracking-wider mb-2.5",
    summaryCard: "bg-gray-50 border border-gray-200 rounded-xl p-3.5 flex flex-col gap-1",
    summaryCategory: "text-[10px] text-blue-600 font-extrabold uppercase",
    summaryName: "text-gray-800 font-bold text-xs",
    summaryRow: "flex items-center justify-between text-xs text-gray-550 mt-2",
    summaryPrice: "font-mono font-bold text-gray-800",
    workshopsTitle: "text-gray-450 font-bold text-xs uppercase tracking-wider mb-2",
    workshopsList: "flex flex-col gap-2.5 max-h-[140px] overflow-y-auto pr-1",
    workshopItem: "bg-gray-50 border border-gray-200 rounded-lg p-2.5 flex items-center justify-between text-xs gap-3",
    workshopMetaWrap: "flex flex-col",
    workshopName: "font-bold text-gray-800 leading-tight",
    workshopMeta: "text-[10px] text-gray-400 mt-0.5",
    workshopPrice: "font-mono text-gray-700 font-bold shrink-0",
    noteBox: "mt-auto bg-blue-50/40 border border-blue-100 p-3.5 rounded-xl flex items-start gap-2.5",
    noteIcon: "w-5 h-5 text-blue-600 shrink-0 mt-0.5",
    noteBody: "text-[11px] text-gray-600 leading-normal",
    noteTitle: "font-semibold text-blue-750 uppercase tracking-wide text-[10px]",
    noteText: "mt-0.5 text-gray-500",
    rightColumn: "flex flex-col justify-between",
    freeBox: "flex-1 flex flex-col items-center justify-center text-center p-8 bg-gray-50 rounded-2xl border border-gray-200",
    freeIcon: "w-12 h-12 text-blue-600 mb-3",
    freeTitle: "text-gray-700 font-bold text-sm",
    freeText: "text-xs text-gray-500 mt-1 max-w-xs",
    paymentBody: "flex-1 flex flex-col gap-5",
    paymentTitle: "text-gray-400 font-bold text-xs uppercase tracking-wider mb-3",
    paymentSwitch: "grid grid-cols-2 bg-gray-100 p-1 rounded-lg border border-gray-200",
    paymentSwitchBtn: "py-2 rounded-md font-bold text-xs uppercase flex items-center justify-center gap-1.5 transition-colors cursor-pointer",
    paymentSwitchActive: "bg-blue-600 text-white shadow-xs",
    paymentSwitchInactive: "text-gray-500 hover:text-gray-800",
    paymentSwitchIcon: "w-4 h-4",
    pixBox: "flex flex-col gap-3.5 bg-gray-50 border border-gray-200 p-4 rounded-xl items-center text-center",
    qrWrap: "w-24 h-24 bg-white p-1.5 rounded-lg shadow-inner border border-gray-100",
    qrImage: "w-full h-full object-contain mix-blend-multiply select-none",
    pixHint: "text-[11px] text-gray-500",
    pixCodeRow: "flex items-center bg-white border border-gray-205 p-2.5 rounded-lg gap-2 mt-2",
    pixCodeInput: "w-full text-[10px] text-gray-400 font-mono bg-transparent outline-none truncate",
    pixCopyBtn: "text-xs text-blue-600 hover:text-blue-700 font-bold shrink-0 flex items-center gap-1 cursor-pointer",
    pixCopyIcon: "w-3.5 h-3.5",
    creditForm: "flex flex-col gap-3",
    fieldLabel: "text-[10px] text-gray-400 uppercase tracking-wide block font-bold mb-1",
    fieldInput: "w-full bg-white border border-gray-200 rounded-lg p-2.5 text-xs text-gray-800 placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-100",
    fieldInputMono: "w-full bg-white border border-gray-200 rounded-lg p-2.5 text-xs text-gray-800 placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-100 font-mono",
    creditGrid: "grid grid-cols-2 gap-3",
    footer: "border-t border-gray-150 mt-6 pt-5 flex flex-col gap-3.5",
    totalRow: "flex items-center justify-between",
    totalLabel: "text-gray-400 font-bold text-xs uppercase",
    totalValueWrap: "text-right",
    totalValue: "text-2xl font-black text-blue-600 font-mono",
    confirmBtn: "w-full bg-blue-600 hover:bg-blue-700 font-black uppercase text-xs tracking-widest py-4 rounded-xl transition-all shadow-md active:scale-98 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50 text-white",
    spinner: "w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin",
    walletIcon: "w-4 h-4",
    successWrap: "p-12 text-center flex flex-col items-center justify-center gap-5 flex-1 select-none bg-white",
    successIconWrap: "w-20 h-20 rounded-full bg-green-50 border border-green-200 flex items-center justify-center animate-bounce text-green-500 mb-2",
    successIcon: "w-10 h-10",
    successTitle: "text-2xl font-black uppercase text-gray-900 tracking-tight",
    successText: "text-xs text-gray-500 max-w-md leading-relaxed",
    successEvent: "font-bold text-gray-800",
    receiptCard: "bg-gray-50 border border-gray-200 p-4 rounded-xl text-left w-full max-w-sm flex flex-col gap-1.5 mt-2 text-gray-700",
    receiptRow: "flex justify-between items-center text-xs",
    receiptLabel: "text-gray-400 leading-none",
    receiptId: "font-mono text-[10px] text-gray-600",
    receiptStatusRow: "flex justify-between items-center text-xs border-t border-gray-150 pt-1.5 mt-1.5",
    receiptStatus: "bg-green-100 text-green-700 font-extrabold text-[9px] px-2 py-0.5 rounded uppercase font-mono border border-green-200",
    successBtn: "mt-6 bg-blue-600 hover:bg-blue-700 text-white font-extrabold uppercase text-xs tracking-wider px-10 py-4 rounded-xl transition-all cursor-pointer shadow-sm",
  },

  layout: {
    container: "max-w-7xl mx-auto px-4 md:px-8 py-8 flex flex-col gap-8",
    flexColGap: "flex flex-col gap-6",
    gridForm: "grid grid-cols-1 md:grid-cols-2 gap-4",
  }
};

// Component specific tokens
export const COMPONENT = {
  ajudaFaq: {
    container: "max-w-4xl mx-auto px-4 py-12 select-none",
    backButton: "mb-8 text-xs text-blue-600 font-extrabold hover:underline flex items-center gap-1.5 uppercase tracking-wider font-mono cursor-pointer",
    headingBadge: "text-[10px] text-blue-600 font-extrabold uppercase tracking-widest font-mono",
    headingTitle: "text-3xl md:text-5xl font-black uppercase tracking-tight text-gray-900 mt-2 leading-tight",
    headingText: "text-sm text-gray-500 mt-3 max-w-2xl font-semibold",
    faqSection: "flex flex-col gap-4",
    faqHeader: "text-xs font-black text-gray-800 uppercase tracking-widest font-mono flex items-center gap-2 mb-2",
    faqCard: "bg-white border border-gray-150 rounded-xl overflow-hidden transition-all shadow-2xs",
    faqButton: "w-full text-left p-4 flex items-center justify-between gap-3 font-semibold text-xs text-gray-800 hover:bg-slate-50 cursor-pointer transition-colors",
    faqAnswer: "p-4 bg-gray-50/50 border-t border-gray-100 text-xs text-gray-550 leading-relaxed font-medium",
    supportCard: "bg-white border border-gray-150 p-6 md:p-8 rounded-2xl shadow-xs",
    supportForm: "flex flex-col gap-4",
    supportSubmit: "w-full bg-blue-600 hover:bg-blue-700 text-white text-[10px] font-bold uppercase tracking-wider py-3 rounded-xl cursor-pointer transition-colors text-center font-mono mt-2"
  },

  certificateView: {
    overlay: "fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs overflow-y-auto px-4 py-8 flex items-center justify-center select-none selection:bg-blue-600 selection:text-white",
    card: "bg-white border border-gray-200/80 w-full max-w-4xl rounded-2xl md:rounded-3xl shadow-2xl relative p-6 md:p-8 flex flex-col gap-6 max-h-[96vh]",
    header: "flex items-center justify-between border-b border-gray-150 pb-3",
    headerTitleWrap: "flex items-center gap-2 text-gray-800",
    headerTitle: "text-gray-950 font-extrabold text-sm uppercase tracking-wider",
    printBtn: "text-yellow-600 border border-yellow-600/30 hover:bg-yellow-50 py-1.5 px-3 rounded-lg text-xs font-bold uppercase tracking-wider flex items-center gap-1.5 cursor-pointer transition-all",
    printIcon: "w-4 h-4",
    closeBtn: "text-gray-400 hover:text-blue-650 transition-colors cursor-pointer",
    printArea: "flex-1 bg-[#fffdf5] text-[#221c0b] p-8 md:p-14 rounded-2xl border-8 border-double border-yellow-700/30 relative flex flex-col justify-between min-h-[520px] shadow-inner text-center font-sans py-12",
    certificateTitleBadge: "text-yellow-800 text-[10px] uppercase font-bold tracking-[6px] block",
    certificateMainTitle: "text-2xl md:text-3.5xl font-serif text-yellow-950 font-semibold tracking-tight uppercase mt-1 leading-none",
    certificateText: "text-gray-700 text-sm md:text-md leading-relaxed font-sans font-light text-justify md:text-center text-gray-800",
    workshopsBox: "bg-yellow-900/5 border border-yellow-850/10 p-3.5 rounded-xl text-left max-w-xl mx-auto w-full relative z-20 shadow-2xs",
    footerRow: "w-full flex flex-col md:flex-row items-center justify-between gap-6 border-t border-yellow-700/10 pt-6 mt-6",
    qrWrap: "bg-white p-1 rounded-md border border-yellow-600/30 w-12 h-12 flex items-center justify-center shrink-0",
  },

  comoFunciona: {
    container: "max-w-4xl mx-auto px-4 py-12 select-none",
    backButton: "mb-8 text-xs text-blue-600 font-extrabold hover:underline flex items-center gap-1.5 uppercase tracking-wider font-mono cursor-pointer",
    headingBadge: "text-[10px] text-blue-600 font-extrabold uppercase tracking-widest font-mono",
    headingTitle: "text-3xl md:text-5xl font-black uppercase tracking-tight text-gray-900 mt-2 leading-tight",
    headingText: "text-sm text-gray-500 mt-3 max-w-2xl font-semibold",
    stepCard: "bg-white border border-gray-150 p-6 rounded-2xl flex flex-col gap-4 shadow-xs relative overflow-hidden group hover:border-blue-300 transition-all duration-200",
    stepIndex: "absolute right-4 top-4 text-3xl font-black text-gray-100 group-hover:text-blue-50 transition-colors font-mono",
    stepIconWrap: "bg-blue-50 w-fit p-3 rounded-xl",
    highlightBanner: "bg-slate-900 text-white rounded-2xl p-6 md:p-8 flex items-center gap-5 flex-wrap md:flex-nowrap",
    highlightIconWrap: "bg-white/10 p-4 rounded-xl shrink-0",
    highlightTitle: "text-sm font-black uppercase tracking-wider text-white",
    highlightText: "text-xs text-gray-300 mt-1.5 leading-relaxed font-semibold",
  },

  dashboardAluno: {
    container: "max-w-7xl mx-auto px-4 md:px-8 mt-10 py-2 select-none selection:bg-blue-600 selection:text-white",
    card: "bg-white rounded-2xl border border-gray-200 p-6 shadow-xs",
    heading: "text-lg font-black uppercase text-gray-800 tracking-tight flex items-center gap-2 mb-1.5",
    subtitle: "text-xs text-gray-500 mb-5 pb-3 border-b border-gray-150",
    emptyBox: "text-center p-8 bg-gray-50 border border-gray-150 rounded-2xl py-12",
    tagSuccess: "bg-green-50 border border-green-150 text-green-700 font-bold text-[9px] uppercase tracking-wide py-0.5 px-2 rounded",
    tagPending: "bg-yellow-50 border border-yellow-150 text-yellow-700 font-bold text-[9px] uppercase tracking-wide py-0.5 px-2 rounded",
    tagCheckin: "bg-blue-50 border border-blue-150 text-blue-700 font-bold text-[9px] uppercase tracking-wide py-0.5 px-2 rounded",
    badgeSmall: "text-[10px] text-blue-600 uppercase font-bold tracking-wider",
    rightPanel: "bg-gray-50 md:w-44 border-l max-md:border-t max-md:border-l-0 border-gray-200 p-5 flex flex-col items-center justify-center text-center gap-2",
    qrButton: "bg-white p-2.5 rounded-lg hover:bg-gray-100 cursor-pointer border border-gray-200 group transition-all",
    qrImage: "w-40 h-40 object-contain mix-blend-multiply select-none",
  }
};
